linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - misspell
    - nilerr
    - prealloc
    - predeclared
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    shadow: true
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  gosec:
    excludes:
      - G104  # unhandled errors — we use errcheck for this

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic
    - path: /testcontainers/
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 5
